### PR TITLE
Alternative side graphic

### PR DESCRIPTION
**Pull request by marcus-j-davies**
- Here I add an alternative side bar graphic.
 
 I'm not sure how you implement it, so attached is only the file needed (as well as the source file)

### CODE REVIEW

**Comment by marcus-j-davies** [comment]
I have not looked too much at the size requirements - so if there is requirement, drop me a line, and I'll size accordingly.

**Comment by ralphwetzel** [comment]
> resolution requirements

That's what the documentation tells us about supported / required resolutions:

```
100%	164x314
125%	192x386
150%	246x459
175%	273x556
200%	328x604
225%	355x700
250%	410x797
```

For now, I think it's fine to have just one. Looks like the figures for 150% are the nearest to your eyeballed size.

BTW: The [change requests](https://discourse.nodered.org/t/node-red-windows-installer/77148/7) are incoming already... 😉

**Comment by marcus-j-davies** [comment]
No worries - I'll update it - and alter it according as per Nick's comment on the forums

**Comment by ralphwetzel** [comment]
@marcus-j-davies 
Could you please change the bit depth to 32bits (RGBA).
24bits - as it's currently - seem to create issues.

**Comment by marcus-j-davies** [comment]
Sure give me a few minutes, and ill raise an updated PR

**Comment by marcus-j-davies** [comment]
@ralphwetzel 

try this one?

[Node_RED_Side_Graphic.bmp.zip](https://github.com/ralphwetzel/node-red-windows-installer/files/11131377/Node_RED_Side_Graphic.bmp.zip)

**Pull request merged**
